name: Build, Check and then push the image

on:
  workflow_dispatch:
    inputs:
      run-workflow:
        type: choice
        options:
          - 'true'
          - 'false'
     
env:
   DOCKER_USERNAME: ${{ fromJson(secrets.DOCKER_SECRETS).docker_username }}
   DOCKER_PASSWORD: ${{ fromJson(secrets.DOCKER_SECRETS).docker_secret_token }}
   IMAGE_NAME: adv-backend-metrics-application
   IMAGE_TAG: latest
   
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Check input and run if true
        if: ${{ github.event.inputs.run-workflow == 'true' }}
        run: |
          echo "Workflow is running."
          
      - name: Check input and exit if false
        if: ${{ github.event.inputs.run-workflow == 'false' }}
        run: exit 1  # Exit the entire workflow with a non-zero code
          
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
          
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Build Docker image
        run: | 
          docker build -t ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      # - name: Run container for health check
      #   run: docker run --rm ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} curl -f http://localhost:7050/health-check  # Replace PORT with your actual health check port

      # - name: Push Docker image to registry
      #   run: docker push ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      
      # - name: Enable Docker experimental features
      #   run: |
      #     echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json
      #     sudo systemctl restart docker

      # - name: Install Docker Buildx
      #   run: |
      #     docker buildx create --use
      #     docker buildx inspect --bootstrap

      # - name: Build Docker image
      #   run: | 
      #     docker buildx build --platform linux/amd64,linux/arm64 -t ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} --file Dockerfile .
      #     docker run -d -p 7050:7050 ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      
      - name: Run container for health check 
        run: |
          docker run -d -p 7050:7050 ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          response=$(curl --write-out '%{http_code}' --silent --output /dev/null http://localhost:7050/health-check)
          if [ "$response" -ne 200 ]; then
            echo "Health check failed with status $response"
            exit 1
          fi
          echo "Health check passed with status $response"
          
      - name: Push Docker image to registry
        run: docker push ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
