name: Build, Check and then push the image

on:
  workflow_dispatch:
    inputs:
      run-workflow:
        type: choice
        options:
          - 'true'
          - 'false'
     
env:
   DOCKER_USERNAME: ${{ fromJson(secrets.DOCKER_SECRETS).docker_username }}
   DOCKER_PASSWORD: ${{ fromJson(secrets.DOCKER_SECRETS).docker_secret_token }}
   IMAGE_NAME: adv-backend-metrics-application
   IMAGE_TAG: latest
   
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Check input and run if true
        if: ${{ github.event.inputs.run-workflow == 'true' }}
        run: |
          echo "Workflow is running."
          
      - name: Check input and exit if false
        if: ${{ github.event.inputs.run-workflow == 'false' }}
        run: exit 1  # Exit the entire workflow with a non-zero code
          
      - uses: actions/checkout@v3
      
      - name: Build Docker image
        run: | 
          docker build -t ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Run container
        run: |
          docker run -d -p 7050:7050 ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          sleep 10
          
      - name: Run container for health check 
        run: |
          response=$(curl --write-out '%{http_code}' --silent --output /dev/null http://localhost:7050/health-check)
          if [ "$response" -ne 200 ]; then
            echo "Health check failed with status $response"
            exit 1
          fi
          echo "Health check passed with status $response"
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
          
      - name: Use Trivy action (official Aqua Security action)
        uses: aquasecurity/trivy-action@master  # Adjust version as needed
        with:
          image-ref: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          output: 'trivy-report.txt'  # Adjust path if needed

      - name: Upload scan results (optional)
        uses: actions/upload-artifact@v3
        with:
          name: trivy-scan-results
          path: ./trivy-report.txt  # Adjust path if using a different format

      - name: Analyze results (optional)
        run: cat ./trivy-report
          
      - name: Push Docker image to registry
        run: docker push ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
