name: Build, Check and then push the image

on:
  workflow_dispatch:
    inputs:
      run-workflow:
        type: choice
        options:
          - 'true'
          - 'false'
     
env:
   DOCKER_USERNAME: ${{ fromJson(secrets.DOCKER_SECRETS).docker_username }}
   DOCKER_PASSWORD: ${{ fromJson(secrets.DOCKER_SECRETS).docker_secret_token }}
   IMAGE_NAME: adv-backend-metrics-application
   IMAGE_TAG: latest
   
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    
      - name: Check input and run if true
        if: ${{ github.event.inputs.run-workflow == 'true' }}
        run: |
          echo "Workflow is running."
          
      - name: Check input and exit if false
        if: ${{ github.event.inputs.run-workflow == 'false' }}
        run: exit 1  # Exit the entire workflow with a non-zero code
        
      - name: Checkout codebase
      - uses: actions/checkout@v3
      
      - name: Build Docker image
        run: | 
          docker build -t ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      # - name: Run container for health check
      #   run: docker run --rm ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} curl -f http://localhost:7050/health-check  # Replace PORT with your actual health check port

      # - name: Push Docker image to registry
      #   run: docker push ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      - name: Run container for testing purpose
        run: |
          docker run -d --name ws1 -p 7050:7050 ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          sleep 10
          
      - name: display container logs
        run: docker logs ws1
        
      - name: Run container for health check 
        run: |
          response=$(curl --write-out '%{http_code}' --silent --output /dev/null http://127.0.0.1:7050/health-check)
          if [ "$response" -ne 200 ]; then
            echo "Health check failed with status $response"
            exit 1
          fi
          echo "Health check passed with status $response"
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
          
      - name: Push Docker image to registry
        run: docker push ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
